[package]
name = "rhi"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
raw-window-handle = "0.6.2"

[dev-dependencies]
winit = "0.29"

[[example]]
name = "Triangle"
path = "examples/triangle.rs"
